# Generated by Django 4.2.6 on 2023-10-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diller", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
