# Generated by Django 3.2.20 on 2023-11-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0002_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diller.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diller.client')),
            ],
        ),
    ]
