# Generated by Django 3.2.20 on 2023-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_manager', 'Approved by Manager'), ('approved_accountant', 'Approved by Accountant'), ('approved_admin', 'Approved by Admin'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
