# Generated by Django 3.2.20 on 2023-11-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diller', '0005_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diller.transaction'),
        ),
    ]
