# Generated by Django 3.2.20 on 2023-11-28 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diller', '0006_auto_20231128_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
